### ISSUE TITLE
full path to wp rest api

### ISSUE THREAD

**Issue by ghost** [thebatclaudio/wp-rest-api-v2-menus#1]
I can't seem to discover the menu routes. Can you provide a full path example with WP REST API?

`<wpsite.com>/wp-json/wp/v2/ ???`

**Comment by thebatclaudio** [comment]
Hi, 
to access to your menus you must call the following route:
`www.yoursite.com/wp-json/menus/v1/menus`

If you want to access to a specific menu you must call the following route:
`www.yoursite.com/wp-json/menus/v1/menus/{slug}`

**Comment by ghost** [comment]
I have an existing menu, so there should be data. I'm running WP 4.5.2 and WP REST API 2.0-beta13.

I get this error

```
{
  code: "rest_invalid_handler",
  message: "The handler for the route is invalid",
  data: {
    status: 500
  }
}
```

**Comment by thebatclaudio** [comment]
Hi, i fixed the bug yesterday. If you remove and reinstall the plugin it should work.

**Comment by ghost** [comment]
It works. You might want to change version number as well. Thanks.

**Comment by thebatclaudio** [comment]
Thank you for the issue! :)

**Comment by thomashagstrom** [comment]
> Hi,
> to access to your menus you must call the following route:
> `www.yoursite.com/wp-json/menus/v1/menus`
> 
> If you want to access to a specific menu you must call the following route:
> `www.yoursite.com/wp-json/menus/v1/menus/{slug}`

Why this isn't the first thing in the readme astounds me. Wouldn't have guessed without this issue

**Comment by thebatclaudio** [comment]
Hi @thomashagstrom,
this plugin extends the standard WP API, so I imagine that who use this plugin knows how [WP API works](https://developer.wordpress.org/rest-api/key-concepts/).

In plugin's readme you can find the RELATIVE path.

For example:

Get all menus: `GET /menus/v1/menus`

It means that you have to add `/menus/v1/menus` to the standard WP API route prefix (that is `http://yoursite.com/wp-json/`)

I'm sorry that it wasn't clear for you, but I didn't expect that someone would use this plugin without knowing how WP API works.
