### ISSUE TITLE
API doesn't return children menu items

### ISSUE THREAD

**Issue by Picksley** [thebatclaudio/wp-rest-api-v2-menus#14]
**Version 0.6**

Parent menu items return fine
Children do not return as nested items under each parent

![image](https://user-images.githubusercontent.com/24915726/55411151-07a3b700-555d-11e9-9add-681e10e960d2.png)

![image](https://user-images.githubusercontent.com/24915726/55411211-243fef00-555d-11e9-8141-652c56507690.png)

**Comment by thebatclaudio** [comment]
Hi @Picksley,
I just tested it on two different Wordpress installation and it works.
Can you give me more info? What version of Wordpress and PHP are you using?

**Comment by Picksley** [comment]
Sure, apologies
I'm using Project Nami v 2.1.1 (Wordpress with SQL at version 5.1.1)
PHP 7.2

**Comment by brnteka** [comment]
i am experiencing the same problem
WordPress 5.2, PHP/7.2.1

**Comment by brnteka** [comment]
this helped -- https://wordpress.org/support/topic/bug-in-submenu-items/

**Comment by thebatclaudio** [comment]
I just released a new version with a bug fix.
Let me know if you find have any issues!

**Comment by Picksley** [comment]
Works perfectly - great work

**Comment by dcblundell** [comment]
> I just released a new version with a bug fix.
> Let me know if you find have any issues!

This doesn't appear to work if you have a further level of navigation. It only gets the first level of child items.

**Comment by wac135** [comment]
Thanks, @thebatclaudio!
However, the new version not supporting more than 2 levels!

**Comment by metawise** [comment]
Thanks, @thebatclaudio.
Unfortunately, the plugin not working for more than 2 levels!
