### ISSUE TITLE
menus/{slug} does not return menu items

### ISSUE THREAD

**Issue by dvdnhm** [thebatclaudio/wp-rest-api-v2-menus#2]
I can get the list of available menus:
![image](https://user-images.githubusercontent.com/6667615/30494254-67ad142a-9a15-11e7-8f6f-664e3658c10f.png)

but when I try /menus/{slug} url, it returns 
![image](https://user-images.githubusercontent.com/6667615/30494306-9050622e-9a15-11e7-93e1-d131833f62da.png)

**Comment by thebatclaudio** [comment]
Hi, which version of Wordpress are you using?

**Comment by dvdnhm** [comment]
I have version 4.8.1

thanks

**Comment by thebatclaudio** [comment]
Hi David,
I fixed the bug and updated the plugin on Wordpress Plugin Directory. Now it should work!
Let me know how it goes and feel free to report other bugs. We really appreciate it!

**Comment by dvdnhm** [comment]
yes, it is working now. thanks.

**Comment by Osamasomy** [comment]
its not workin in WordPress 5.1.1

**Comment by Picksley** [comment]
@thebatclaudio Could we possibly re-open this issue?
This issue is present again in WP 5.1.0 & 5.1.1

**Comment by thebatclaudio** [comment]
Hi @Picksley and @Osamasomy, 
sorry but I didn't read the notification. I reopen the issue and tonight I will check if it works.
However, I released a new version of the plugin. Can you check if it works?

**Comment by Picksley** [comment]
> Hi @Picksley and @Osamasomy,
> sorry but I didn't read the notification. I reopen the issue and tonight I will check if it works.
> However, I released a new version of the plugin. Can you check if it works?

Works perfectly again on returning the menu for me on **Version 0.6**  - great work, thanks @thebatclaudio 

Just an issue with the API only returning the parents and not the children but will raise a new bug for you
