### ISSUE TITLE
Thanks for the plugin!

### ISSUE THREAD

**Issue by JAZzmiX** [thebatclaudio/wp-rest-api-v2-menus#20]
On the last update you added slug to item object but it work from pages & posts, not for category. 

in  JS I took slug from url like: 

```javascript
  const getSlug = url => {
    const parts = url.split('/');
    return parts.length > 2 ? parts[parts.length - 2] : '';
  };
....
getSlug(item.url);
```

**Comment by thebatclaudio** [comment]
Hi @JAZzmiX,
thank you for your issue. I will fix this asap!
