### ISSUE TITLE
Query by slug 

### ISSUE THREAD

**Issue by bitfactory-lasse-vandenboschchristensen** [thebatclaudio/wp-rest-api-v2-menus#23]
Hi,
Is it possible to query by slug name? such as ```rest_route=/menus/v1/menus&slug=main-menu```

All the best,
Lasse

**Comment by thebatclaudio** [comment]
Hi @bitfactory-lasse-vandenboschchristensen ,
of course you can do it.

The URL is: http://{YOUR_WORDPRESS}/wp-json/menus/v1/menus/{YOUR_SLUG}
