### ISSUE TITLE
post_name of item inconsistency

### ISSUE THREAD

**Issue by mgiraldo** [thebatclaudio/wp-rest-api-v2-menus#4]
- WP version: 4.9.1 
- WP Menus v2 version: 0.3

i am using this plugin with wp `page` types. menus are created properly but at some point the `post_name` for each items went from being the `slug` to the `id`. eg: from `post_name: "about-us"` to `post_name: "6893"`. the logic in the app requires it to be the slug. old pages still show the slug but any new pages i create appear in the menu with their id. any idea what could have gone wrong?

**Comment by mgiraldo** [comment]
ok so turns out the reason is that if the menu item is a `page`, the `post_name` is the page ID whereas if I make a “Custom Link” and point it to the corresponding `/wp-json/wp/v2/pages/ID` link then the `post_name` is the slug.

**Comment by thebatclaudio** [comment]
Hi, I'm using the **wp_get_nav_menu_items** Wordpress function. As you said, if the page hasn't got a slug it will return its id instead of its slug.

**Comment by mgiraldo** [comment]
but the pages _do_ have slugs:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/133020/34796842-deb3a60e-f624-11e7-8bda-afa0e125d2e5.png">

or is there another field somewhere that i'm not adding?

**Comment by thebatclaudio** [comment]
As you can see in wp-rest-api-v2-menus.php on line 36, I simply populate the items attribute using wp_get_nav_menu_items function, that is a standard Wordpress function.
I don't know the reason, but it work in this way. You can use **/wp-json/wp/v2/pages/:object_id** endpoint to get page's data and get your slug.

**Comment by FDiskas** [comment]
So sad. Can't generate menus with correct urls in SPA. The best what I can get is the url. And that url of course is my rest api endpoint :( :ambulance:
