### ISSUE TITLE
Get custom fields

### ISSUE THREAD

**Issue by nathanqueija** [thebatclaudio/wp-rest-api-v2-menus#5]
Hello,

Is there a way to get custom fields added to Menu items?
Thanks

**Comment by thebatclaudio** [comment]
Hello,
did you use a plugin to add custom fields to menu items? If yes, which plugin?

**Comment by colby-moffett** [comment]
You can use ACF to add custom fields to the menu item, however you can not query them in the API. That would definitely be a nice addition.

**Comment by thebatclaudio** [comment]
Support for menu item's custom fields

a34c2f41692c13ab27255fa7c9f44a6f1ce0e4ab
